### ISSUE TITLE
Products with variants should not be able to be added to cart

### ISSUE THREAD

**Issue by eufandem** [chec/commercejs-chopchop-demo#15]
I get an error at the checkout (no context). I was able to add a product without a variant selected into the cart.

<img width="1769" alt="Screen Shot 2021-01-27 at 3 47 34 PM" src="https://user-images.githubusercontent.com/29156467/106069288-199e0480-60b7-11eb-97be-39bfe773b07e.png">

**Comment by notrab** [comment]
@eufandem this is the error we discussed earlier, which is that the checkout endpoint doesn't bring along the selected variant IDs.

As @ScopeyNZ suggested previously, it would be good if the API handled this, since it already knows about it, instead of jumping through hoops on the frontend.

**Comment by eufandem** [comment]
OK so whats the solution here? @robbieaverill @ScopeyNZ does it make sense to add this to the API or @notrab are we going to do some hoop jumping?

**Comment by notrab** [comment]
@eufandem I'd prefer not to, merely because it isn't the best representation for the API. But if we _really_ want to, I'll do some hoop jumping.

**Comment by eufandem** [comment]
Ping @ScopeyNZ @robbieaverill on the API route

**Comment by robbieaverill** [comment]
Seems like a reasonable API change to me. To confirm, the situation is that you've already chosen a variant and added the product to your cart, so the checkout should remember that the variant has been selected? It already remembers the line items you've added, just not the variant selected for it?

**Comment by eufandem** [comment]
Nice let's do it

**Comment by ScopeyNZ** [comment]
We have an issue on our API repo for this: https://github.com/chec/api.v1/issues/1097

**Comment by robbieaverill** [comment]
I can pick it up today

**Comment by robbieaverill** [comment]
Fix going out now
