### ISSUE TITLE
Allow the browser back button to close the cart

### ISSUE THREAD

**Issue by ScopeyNZ** [chec/commercejs-chopchop-demo#16]
Clicking the back button changes the URL but doesn't take you out of the cart.

![CleanShot 2021-01-27 at 16 10 10](https://user-images.githubusercontent.com/3260989/106072164-88319100-60bc-11eb-9c88-8bbaee5cf81b.gif)

**Comment by notrab** [comment]
Will look into this. It's a little trickier than just implementing a handler for the router since the modal presence is controlled using framer motion `useCycle`.

So adding:

```js
useEffect(() => {
    router.events.on("routeChangeStart", closeModal);

    return () => {
      router.events.off("routeChangeStart", closeModal);
    };
  }, []);
```

will cause the modal to cycle through `true`/`false`, which is even more annoying.
