### ISSUE TITLE
Billing address region dropdown gets stuck on some other country

### ISSUE THREAD

**Issue by robbieaverill** [chec/commercejs-chopchop-demo#22]
![image](https://user-images.githubusercontent.com/5170590/106073259-8cf74480-60be-11eb-83ec-1927051368b9.png)

When you first fill out this form, click into the country field and type "Canada". Notice that when you press "C" it starts to load subdivisions for some other country like Cameroon or something. The state field is then updated with the subdivisions for that country. When Canada ends up being selected the region dropdown doesn't change to Canadian subdivisions, so I have to change the country to something else and back again with my mouse.

**Comment by notrab** [comment]
Good catch @robbieaverill! What's your thoughts here? Throw in a debounce of sorts?

**Comment by robbieaverill** [comment]
Yeah I reckon so 👍
