### ISSUE TITLE
Integrate PayPal

### ISSUE THREAD

**Issue by IvanSmiths** [chec/commercejs-chopchop-demo#33]
Hi all. Does anyone have tried to integrates the PayPal checkout? I'm trying to do it but i'm feeling kind of lost.

**Comment by ScopeyNZ** [comment]
Hi Ivan. There's some specific docs for this in the Commerce.js docs: https://commercejs.com/docs/guides/paypal-integration. If you still need help - you might find it easier to find help in the community Slack: http://slack.commercejs.com/
